### ISSUE TITLE
"design:type" return undefined if types are defined out of order.

### ISSUE THREAD

**Issue by abdullah2993** [rbuckton/reflect-metadata#129]
If the order of declaration of A and B is changed then it works otherwise it doesn't 
```
import 'reflect-metadata';

function field(target: Object, propertyName: string) {}
export class C {}

export class A {
  @field
  public bb: B;

  @field
  public cc: C;

  @field
  public xx: boolean;
}

export class B {
  @field
  public aa: A;
}

console.log(Reflect.getOwnMetadata('design:type', A.prototype, 'bb')); // Return undefined expected B
console.log(Reflect.getOwnMetadata('design:type', A.prototype, 'cc'));
console.log(Reflect.getOwnMetadata('design:type', A.prototype, 'xx'));
```

**Comment by abdullah2993** [comment]
Closing this since this is related to typescript compiler

**Comment by rezonant** [comment]
Yes it's a known limitation of the way TS emits design:type. Proposed alternative formats use the "type resolver" pattern instead, which would store a function that returned the type instead of the type itself. Unfortunately, TS can't change this without breaking compatibility, and they are waiting for progress on the decorator proposal before revisiting anything about decorators, and based on the team's statements, they might never revisit or enhance RTTI.

I am working on a transformer to comprehensively replace design:type et al with a system that emits all type metadata, not just items that are decorated, and it does use type resolvers to eliminate this issue https://github.com/rezonant/typescript-rtti
