### ISSUE TITLE
process.env check outputs complete dump of environment settings

### ISSUE THREAD

**Issue by Guzzter** [rbuckton/reflect-metadata#142]
We are using a NPM package that depends on this package. When compiling to JS, I see that it contains all my environment settings with local paths, etc:

{....A LOT OF ENV SETTINGS...}.REFLECT_METADATA_USE_MAP_POLYFILL === "true"

If I look into following line 678, it looks like a coding error. It supposed to do a check, but in my case it outputs a complete dump of settings:
https://github.com/rbuckton/reflect-metadata/blob/3aeb98af4030be664a66f49bfd164936e0ba1825/Reflect.ts#L678C60-L678C60

I am using Windows. Am I right? Is this something that can be fixed?

**Comment by ljharb** [comment]
Are you using a bundler? A bundler might be inserting the entire `process.env` object there, although it shouldn't. The code could also do `!!process.env` if that was a problem worth preventing.

**Comment by rbuckton** [comment]
This definitely sounds like something a bundler is doing, which is unfortunate because the point of the other checks on that line are to only test for the environment variable in a host that actually supports it.

> The code could also do `!!process.env` if that was a problem worth preventing.

Are you indicating that `!!process.env` would bypass the bundler injecting an object here? It's already checking for the presence of `env` via `&&`:
```js
const usePolyfill = typeof process === "object" && process.env && process.env["REFLECT_METADATA_USE_MAP_POLYFILL"] === "true";
//                                                 ^^^^^^^^^^^
```

So unless the `!!` is some kind of heuristic a bundler recognizes, I'm not sure it will be much help.

The only other thing I could think to do is do something like `process["en" + "v"]` or similar, assuming that's enough to bypass a bundler.

**Comment by ljharb** [comment]
True - I would assume/hope that a bundler that is providing `process` would know that `process` and `process.env` are always an object, and thus the boolean would be replaced by `true` and then go through DCE.

I'd still love to know which bundler tho, since that sounds like a pretty bad bug.

**Comment by janeklb** [comment]
I'm using `webpack` via `nx` and am also encountering this problem.
`nx` uses webpack's `DefinePlugin` to automatically load all envars starting with `NX_` into `process.env`. As a result, if `reflect-metadata` is included in the bundle, all the the envars getting included in the bundler's output.

Granted this behaviour is not a bug; however, it does result in some undesirable behaviour (envars being included into your bundle). Given that `process.env` is used to see if polyfills should be included, could you expose an additional polyfill-less entrypoint (eg. `import 'reflect-metadata/no-polyfills';`)? This would also probably address https://github.com/rbuckton/reflect-metadata/issues/73
