### ISSUE TITLE
Reflect-Metadata update breaks Nest+TypeORM

### ISSUE THREAD

**Issue by alper** [rbuckton/reflect-metadata#160]
I think there should be awareness here as well that an update to this package has rippled out to two very large projects and the version incompatibility breaks them entirely.

It's also very hard to debug without outside assistance.

See the discussion and resolution here: https://github.com/typeorm/typeorm/issues/10671#issuecomment-1931628948

**Comment by rbuckton** [comment]
It's not clear to me from that thread what the exact issue is. `reflect-metadata@0.2` added a shared metadata registry so that the default export as well as the new `/lite` and `/no-conflict` exports could interoperate, and it should have been backwards compatible with older versions of `reflect-metadata`.
