### ISSUE TITLE
IE8 expected identifier error

### ISSUE THREAD

**Issue by loliparra80** [rbuckton/reflect-metadata#46]
When I try to open my website in a internet explorer ie8, doesn't work. While in IE11 I have no problems.

When I debug the error is: "Expected identifier" Reflect.js, line 516 character 26. It seems like don't recognize the "delete" on "if(!metadataMap.delete(metadataKey)) return false".

What can I do?
Thanks.

**Comment by tytskiy** [comment]
@loliparra80 there is an issue, because reserved keyword is used as a method name.

I assume that your use-case is Angular2 - Angular2 doesn't even commit to support IE9 at the time of writing this.

Refer to browser support badges in their repo: https://github.com/angular/angular/blob/master/README.md

**Comment by rbuckton** [comment]
@tytskiy is correct. `reflect-metadata` depends on a minimum of ECMAScript 5, which is not supported in IE8.
