### ISSUE TITLE
reflect-metadata@0.1.9 may be not compatible with 0.1.3

### ISSUE THREAD

**Issue by zzx88991** [rbuckton/reflect-metadata#55]
Hi, 

I have reflect-metadata@0.1.3 installed on my machine, and  
```
  "dependencies": {
      "reflect-metadata": "^0.1.3",
  }
```
 in the my packages.json's dependency list. 

Yesterday when i restore the all the node modules, npm picked up reflect-metadata@0.1.9 for me, which results an compiling error:

`Build:Cannot find name 'Record'.	...\reflect-metadata\Reflect.ts	   20`

I am not 100% if that is compatibility issue, but thank you for taking a look.

**Comment by rbuckton** [comment]
@zzx88991 Reflect-metadata 0.1.9 depends on TypeScript 2.1. As far as version to version compatibility, according to [semver](http://semver.org/#spec-item-4):

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

I could bump the minor version to 0.2.0, but if you require a specific version of reflect-metadata, I would recommend you specify an explicit version in your `package.json` rather than rely on a [caret version](https://www.npmjs.com/package/semver#caret-ranges-123-025-004). 

I do find it odd that an npm package restore resulted in a compilation of `Reflect.ts` as it should have been excluded from the published npm package.

**Comment by zzx88991** [comment]
Thanks. The version of Typescript I am using is 2.0. 

It is good to go with specifying 0.1.3 in the `package.json`
